version: '3'

services:
  varnish:
    container_name: ${DOMAIN}_varnish
    build:
      context: ./services/varnish
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        VARNISH_MEMORY: ${VARNISH_MEMORY}
    environment:
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN}
    restart: always
    depends_on:
      - nginx

  nginx:
    container_name: ${DOMAIN}_nginx
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    restart: always
    volumes:
      - code:/code
    depends_on:
      - php

  php:
    container_name: ${DOMAIN}_php
    build:
      context: ./services/php
      args:
        PHP_VERSION: ${PHP_VERSION}
    restart: always
    volumes:
      - code:/code
    depends_on:
      - mysql
      - wordpress

  mysql:
    container_name: ${DOMAIN}_mysql
    image: mysql:${MYSQL_VERSION}
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    container_name: ${DOMAIN}_wordpress
    build:
      context: ./services/wordpress
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        W3_TOTAL_CACHE_VERSION: ${W3_TOTAL_CACHE_VERSION}
    volumes:
      - code:/code

  exim:
    container_name: ${DOMAIN}_exim
    build:
      context: ./services/exim
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    dns: ${EXIM_DNS}
    restart: always

volumes:
    code:
    mysql_data: